name: Build

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["$default-branch"]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Cancelar ejecuciones anteriores
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - name: Instalar node
        uses: actions/setup-node@v2
        with:
          cache: npm
          node-version: "16.14.2"
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Build Library
        run: npm run build
      - name: Test action
        uses: jscode-es/action_ssh
